// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjsgcfhDGJSAXOtXBvdh_OpLpzDLkkMJA',
    appId: '1:659294961629:web:f500be69514923df5ac034',
    messagingSenderId: '659294961629',
    projectId: 'napphyservices',
    authDomain: 'napphyservices.firebaseapp.com',
    storageBucket: 'napphyservices.firebasestorage.app',
    measurementId: 'G-GM4FGFF6WR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBs7DSH29KI0tlnwaQ-A1lXLioqF5MPGfg',
    appId: '1:659294961629:android:a84cc777c757840f5ac034',
    messagingSenderId: '659294961629',
    projectId: 'napphyservices',
    storageBucket: 'napphyservices.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAC92xe1SFQEJXsnkxqqvJs2JI8lMjv880',
    appId: '1:659294961629:ios:58436e785ff244e85ac034',
    messagingSenderId: '659294961629',
    projectId: 'napphyservices',
    storageBucket: 'napphyservices.firebasestorage.app',
    iosBundleId: 'com.napphy.services',
  );

}